INCLUDE = -I /home/yangyan/boost_1_50_0/
LIBS	= -lboost_serialization -lboost_system -lboost_thread
CC	= g++
DEBUG	= -g

SOURCE	= test.cpp 

test: $(SOURCE)
	$(CC) $(DEBUG) $(INCLUDE) $(LIBS) -o $@ $^ 
